services:
  postgres:
    image: postgres:15-alpine
    container_name: writtenlyhub_postgres
    environment:
      POSTGRES_USER: payload
      POSTGRES_PASSWORD: payloadpassword
      POSTGRES_DB: writtenlyhub
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
