/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    tags: Tag;
    blogs: Blog;
    subscribers: Subscriber;
    'success-stories': SuccessStory;
    'success-story-categories': SuccessStoryCategory;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    'success-stories': SuccessStoriesSelect<false> | SuccessStoriesSelect<true>;
    'success-story-categories': SuccessStoryCategoriesSelect<false> | SuccessStoryCategoriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'homepage-settings': HomepageSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'homepage-settings': HomepageSettingsSelect<false> | HomepageSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Auto-generated from name if left blank.
   */
  slug?: string | null;
  avatar?: (number | null) | Media;
  role: 'admin' | 'author';
  designation?: string | null;
  bio?: string | null;
  linkedin?: string | null;
  twitter?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Auto-generated from name if left blank.
   */
  slug?: string | null;
  description?: string | null;
  /**
   * Hex color code (e.g., #FF0000)
   */
  color?: string | null;
  seo?: {
    /**
     * Recommended length: 50-60 characters. Falls back to post title.
     */
    metaTitle?: string | null;
    /**
     * Recommended length: 150-160 characters. Falls back to excerpt.
     */
    metaDescription?: string | null;
    /**
     * Leave blank to auto-generate from site URL and slug.
     */
    canonicalUrl?: string | null;
    /**
     * Enter the main keyword you want this page to rank for.
     */
    focusKeyword?: string | null;
    dismissedWarnings?:
      | {
          ruleId?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Falls back to Meta Title
     */
    ogTitle?: string | null;
    /**
     * Falls back to Meta Description
     */
    ogDescription?: string | null;
    /**
     * Falls back to Featured Image, then Global Default, then Generated Image
     */
    ogImage?: (number | null) | Media;
    /**
     * Falls back to Open Graph Title
     */
    twitterTitle?: string | null;
    /**
     * Falls back to Open Graph Description
     */
    twitterDescription?: string | null;
    /**
     * Falls back to Open Graph Image
     */
    twitterImage?: (number | null) | Media;
    /**
     * Override global robot meta tags for this specific page.
     */
    robots?: {
      /**
       * Allow search engines to index pages
       */
      index?: boolean | null;
      /**
       * Prevent indexing
       */
      noindex?: boolean | null;
      /**
       * Allow following links
       */
      follow?: boolean | null;
      /**
       * Prevent following links
       */
      nofollow?: boolean | null;
      /**
       * Do not show a cached link in search results
       */
      noarchive?: boolean | null;
      /**
       * Do not show a text snippet or video preview
       */
      nosnippet?: boolean | null;
      /**
       * Do not index images on this page
       */
      noimageindex?: boolean | null;
      /**
       * Maximum text-snippet length (in characters)
       */
      maxSnippet?: number | null;
      /**
       * Maximum size of an image preview
       */
      maxImagePreview?: ('none' | 'standard' | 'large') | null;
      /**
       * Maximum video snippet length (in seconds)
       */
      maxVideoPreview?: number | null;
    };
    jsonLd?: {
      faq?:
        | {
            question: string;
            answer: string;
            id?: string | null;
          }[]
        | null;
      howTo?: {
        name?: string | null;
        description?: string | null;
        step?:
          | {
              name: string;
              text: string;
              url?: string | null;
              image?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
      };
      /**
       * Valid JSON array or object to merge/append with generated schemas.
       */
      advancedOverride?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  /**
   * Auto-generated from name if left blank.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  title: string;
  excerpt?: string | null;
  featuredImage: number | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  seo?: {
    /**
     * Recommended length: 50-60 characters. Falls back to post title.
     */
    metaTitle?: string | null;
    /**
     * Recommended length: 150-160 characters. Falls back to excerpt.
     */
    metaDescription?: string | null;
    /**
     * Leave blank to auto-generate from site URL and slug.
     */
    canonicalUrl?: string | null;
    /**
     * Enter the main keyword you want this page to rank for.
     */
    focusKeyword?: string | null;
    dismissedWarnings?:
      | {
          ruleId?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Falls back to Meta Title
     */
    ogTitle?: string | null;
    /**
     * Falls back to Meta Description
     */
    ogDescription?: string | null;
    /**
     * Falls back to Featured Image, then Global Default, then Generated Image
     */
    ogImage?: (number | null) | Media;
    /**
     * Falls back to Open Graph Title
     */
    twitterTitle?: string | null;
    /**
     * Falls back to Open Graph Description
     */
    twitterDescription?: string | null;
    /**
     * Falls back to Open Graph Image
     */
    twitterImage?: (number | null) | Media;
    /**
     * Override global robot meta tags for this specific page.
     */
    robots?: {
      /**
       * Allow search engines to index pages
       */
      index?: boolean | null;
      /**
       * Prevent indexing
       */
      noindex?: boolean | null;
      /**
       * Allow following links
       */
      follow?: boolean | null;
      /**
       * Prevent following links
       */
      nofollow?: boolean | null;
      /**
       * Do not show a cached link in search results
       */
      noarchive?: boolean | null;
      /**
       * Do not show a text snippet or video preview
       */
      nosnippet?: boolean | null;
      /**
       * Do not index images on this page
       */
      noimageindex?: boolean | null;
      /**
       * Maximum text-snippet length (in characters)
       */
      maxSnippet?: number | null;
      /**
       * Maximum size of an image preview
       */
      maxImagePreview?: ('none' | 'standard' | 'large') | null;
      /**
       * Maximum video snippet length (in seconds)
       */
      maxVideoPreview?: number | null;
    };
    jsonLd?: {
      faq?:
        | {
            question: string;
            answer: string;
            id?: string | null;
          }[]
        | null;
      howTo?: {
        name?: string | null;
        description?: string | null;
        step?:
          | {
              name: string;
              text: string;
              url?: string | null;
              image?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
      };
      /**
       * Valid JSON array or object to merge/append with generated schemas.
       */
      advancedOverride?: string | null;
    };
  };
  previousSlugs?:
    | {
        slug?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Auto-generated from title if left blank.
   */
  slug?: string | null;
  author: number | User;
  category: number | Category;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  publishedAt?: string | null;
  lastUpdated?: string | null;
  /**
   * Estimated read time (auto-calculated)
   */
  readTime?: string | null;
  featuredHero?: boolean | null;
  featuredArticle?: boolean | null;
  sticky?: boolean | null;
  relatedArticles?: (number | Blog)[] | null;
  searchDocument?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  /**
   * First name of the subscriber (optional)
   */
  firstName?: string | null;
  status: 'active' | 'pending' | 'unsubscribed';
  /**
   * Where this subscriber signed up from (e.g., Blog Popup, Inline Form, Footer, Article CTA)
   */
  source?: string | null;
  subscribedAt?: string | null;
  confirmationToken?: string | null;
  confirmationTokenExpiresAt?: string | null;
  confirmedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "success-stories".
 */
export interface SuccessStory {
  id: number;
  title: string;
  clientName: string;
  clientLogo: number | Media;
  category: number | SuccessStoryCategory;
  shortDescription: string;
  featuredImage: number | Media;
  summaryHeading?: string | null;
  summaryBullets?:
    | {
        point: string;
        id?: string | null;
      }[]
    | null;
  metrics?:
    | {
        value: string;
        label: string;
        optionalVisual?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  strategyEyebrow?: string | null;
  strategyHeading?: string | null;
  strategyDescription?: string | null;
  strategyVisual?: (number | null) | Media;
  problemHeading?: string | null;
  problemDescription?: string | null;
  problemPoints?:
    | {
        heading: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  beforeImage?: (number | null) | Media;
  afterImage?: (number | null) | Media;
  impactHeading?: string | null;
  impactDescription?: string | null;
  impactVisual?: (number | null) | Media;
  solutionBlocks?:
    | {
        heading: string;
        bodyCopy: string;
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  clientDescription?: string | null;
  clientVisual?: (number | null) | Media;
  testimonial?: {
    quote?: string | null;
    name?: string | null;
    role?: string | null;
    image?: (number | null) | Media;
  };
  seo?: {
    /**
     * Recommended length: 50-60 characters. Falls back to post title.
     */
    metaTitle?: string | null;
    /**
     * Recommended length: 150-160 characters. Falls back to excerpt.
     */
    metaDescription?: string | null;
    /**
     * Leave blank to auto-generate from site URL and slug.
     */
    canonicalUrl?: string | null;
    /**
     * Enter the main keyword you want this page to rank for.
     */
    focusKeyword?: string | null;
    dismissedWarnings?:
      | {
          ruleId?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Falls back to Meta Title
     */
    ogTitle?: string | null;
    /**
     * Falls back to Meta Description
     */
    ogDescription?: string | null;
    /**
     * Falls back to Featured Image, then Global Default, then Generated Image
     */
    ogImage?: (number | null) | Media;
    /**
     * Falls back to Open Graph Title
     */
    twitterTitle?: string | null;
    /**
     * Falls back to Open Graph Description
     */
    twitterDescription?: string | null;
    /**
     * Falls back to Open Graph Image
     */
    twitterImage?: (number | null) | Media;
    /**
     * Override global robot meta tags for this specific page.
     */
    robots?: {
      /**
       * Allow search engines to index pages
       */
      index?: boolean | null;
      /**
       * Prevent indexing
       */
      noindex?: boolean | null;
      /**
       * Allow following links
       */
      follow?: boolean | null;
      /**
       * Prevent following links
       */
      nofollow?: boolean | null;
      /**
       * Do not show a cached link in search results
       */
      noarchive?: boolean | null;
      /**
       * Do not show a text snippet or video preview
       */
      nosnippet?: boolean | null;
      /**
       * Do not index images on this page
       */
      noimageindex?: boolean | null;
      /**
       * Maximum text-snippet length (in characters)
       */
      maxSnippet?: number | null;
      /**
       * Maximum size of an image preview
       */
      maxImagePreview?: ('none' | 'standard' | 'large') | null;
      /**
       * Maximum video snippet length (in seconds)
       */
      maxVideoPreview?: number | null;
    };
    jsonLd?: {
      faq?:
        | {
            question: string;
            answer: string;
            id?: string | null;
          }[]
        | null;
      howTo?: {
        name?: string | null;
        description?: string | null;
        step?:
          | {
              name: string;
              text: string;
              url?: string | null;
              image?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
      };
      /**
       * Valid JSON array or object to merge/append with generated schemas.
       */
      advancedOverride?: string | null;
    };
  };
  /**
   * Auto-generated from title if left blank.
   */
  slug?: string | null;
  publishedDate?: string | null;
  lastUpdated?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "success-story-categories".
 */
export interface SuccessStoryCategory {
  id: number;
  name: string;
  /**
   * Auto-generated from name if left blank.
   */
  slug?: string | null;
  description?: string | null;
  /**
   * Hex color code (e.g., #FF0000)
   */
  color?: string | null;
  seo?: {
    /**
     * Recommended length: 50-60 characters. Falls back to post title.
     */
    metaTitle?: string | null;
    /**
     * Recommended length: 150-160 characters. Falls back to excerpt.
     */
    metaDescription?: string | null;
    /**
     * Leave blank to auto-generate from site URL and slug.
     */
    canonicalUrl?: string | null;
    /**
     * Enter the main keyword you want this page to rank for.
     */
    focusKeyword?: string | null;
    dismissedWarnings?:
      | {
          ruleId?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Falls back to Meta Title
     */
    ogTitle?: string | null;
    /**
     * Falls back to Meta Description
     */
    ogDescription?: string | null;
    /**
     * Falls back to Featured Image, then Global Default, then Generated Image
     */
    ogImage?: (number | null) | Media;
    /**
     * Falls back to Open Graph Title
     */
    twitterTitle?: string | null;
    /**
     * Falls back to Open Graph Description
     */
    twitterDescription?: string | null;
    /**
     * Falls back to Open Graph Image
     */
    twitterImage?: (number | null) | Media;
    /**
     * Override global robot meta tags for this specific page.
     */
    robots?: {
      /**
       * Allow search engines to index pages
       */
      index?: boolean | null;
      /**
       * Prevent indexing
       */
      noindex?: boolean | null;
      /**
       * Allow following links
       */
      follow?: boolean | null;
      /**
       * Prevent following links
       */
      nofollow?: boolean | null;
      /**
       * Do not show a cached link in search results
       */
      noarchive?: boolean | null;
      /**
       * Do not show a text snippet or video preview
       */
      nosnippet?: boolean | null;
      /**
       * Do not index images on this page
       */
      noimageindex?: boolean | null;
      /**
       * Maximum text-snippet length (in characters)
       */
      maxSnippet?: number | null;
      /**
       * Maximum size of an image preview
       */
      maxImagePreview?: ('none' | 'standard' | 'large') | null;
      /**
       * Maximum video snippet length (in seconds)
       */
      maxVideoPreview?: number | null;
    };
    jsonLd?: {
      faq?:
        | {
            question: string;
            answer: string;
            id?: string | null;
          }[]
        | null;
      howTo?: {
        name?: string | null;
        description?: string | null;
        step?:
          | {
              name: string;
              text: string;
              url?: string | null;
              image?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
      };
      /**
       * Valid JSON array or object to merge/append with generated schemas.
       */
      advancedOverride?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'blogs';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'success-stories';
        value: number | SuccessStory;
      } | null)
    | ({
        relationTo: 'success-story-categories';
        value: number | SuccessStoryCategory;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  avatar?: T;
  role?: T;
  designation?: T;
  bio?: T;
  linkedin?: T;
  twitter?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  color?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        focusKeyword?: T;
        dismissedWarnings?:
          | T
          | {
              ruleId?: T;
              id?: T;
            };
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        twitterTitle?: T;
        twitterDescription?: T;
        twitterImage?: T;
        robots?:
          | T
          | {
              index?: T;
              noindex?: T;
              follow?: T;
              nofollow?: T;
              noarchive?: T;
              nosnippet?: T;
              noimageindex?: T;
              maxSnippet?: T;
              maxImagePreview?: T;
              maxVideoPreview?: T;
            };
        jsonLd?:
          | T
          | {
              faq?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              howTo?:
                | T
                | {
                    name?: T;
                    description?: T;
                    step?:
                      | T
                      | {
                          name?: T;
                          text?: T;
                          url?: T;
                          image?: T;
                          id?: T;
                        };
                  };
              advancedOverride?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  featuredImage?: T;
  content?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        focusKeyword?: T;
        dismissedWarnings?:
          | T
          | {
              ruleId?: T;
              id?: T;
            };
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        twitterTitle?: T;
        twitterDescription?: T;
        twitterImage?: T;
        robots?:
          | T
          | {
              index?: T;
              noindex?: T;
              follow?: T;
              nofollow?: T;
              noarchive?: T;
              nosnippet?: T;
              noimageindex?: T;
              maxSnippet?: T;
              maxImagePreview?: T;
              maxVideoPreview?: T;
            };
        jsonLd?:
          | T
          | {
              faq?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              howTo?:
                | T
                | {
                    name?: T;
                    description?: T;
                    step?:
                      | T
                      | {
                          name?: T;
                          text?: T;
                          url?: T;
                          image?: T;
                          id?: T;
                        };
                  };
              advancedOverride?: T;
            };
      };
  previousSlugs?:
    | T
    | {
        slug?: T;
        id?: T;
      };
  slug?: T;
  author?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  publishedAt?: T;
  lastUpdated?: T;
  readTime?: T;
  featuredHero?: T;
  featuredArticle?: T;
  sticky?: T;
  relatedArticles?: T;
  searchDocument?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  firstName?: T;
  status?: T;
  source?: T;
  subscribedAt?: T;
  confirmationToken?: T;
  confirmationTokenExpiresAt?: T;
  confirmedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "success-stories_select".
 */
export interface SuccessStoriesSelect<T extends boolean = true> {
  title?: T;
  clientName?: T;
  clientLogo?: T;
  category?: T;
  shortDescription?: T;
  featuredImage?: T;
  summaryHeading?: T;
  summaryBullets?:
    | T
    | {
        point?: T;
        id?: T;
      };
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        optionalVisual?: T;
        id?: T;
      };
  strategyEyebrow?: T;
  strategyHeading?: T;
  strategyDescription?: T;
  strategyVisual?: T;
  problemHeading?: T;
  problemDescription?: T;
  problemPoints?:
    | T
    | {
        heading?: T;
        description?: T;
        id?: T;
      };
  beforeImage?: T;
  afterImage?: T;
  impactHeading?: T;
  impactDescription?: T;
  impactVisual?: T;
  solutionBlocks?:
    | T
    | {
        heading?: T;
        bodyCopy?: T;
        image?: T;
        id?: T;
      };
  clientDescription?: T;
  clientVisual?: T;
  testimonial?:
    | T
    | {
        quote?: T;
        name?: T;
        role?: T;
        image?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        focusKeyword?: T;
        dismissedWarnings?:
          | T
          | {
              ruleId?: T;
              id?: T;
            };
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        twitterTitle?: T;
        twitterDescription?: T;
        twitterImage?: T;
        robots?:
          | T
          | {
              index?: T;
              noindex?: T;
              follow?: T;
              nofollow?: T;
              noarchive?: T;
              nosnippet?: T;
              noimageindex?: T;
              maxSnippet?: T;
              maxImagePreview?: T;
              maxVideoPreview?: T;
            };
        jsonLd?:
          | T
          | {
              faq?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              howTo?:
                | T
                | {
                    name?: T;
                    description?: T;
                    step?:
                      | T
                      | {
                          name?: T;
                          text?: T;
                          url?: T;
                          image?: T;
                          id?: T;
                        };
                  };
              advancedOverride?: T;
            };
      };
  slug?: T;
  publishedDate?: T;
  lastUpdated?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "success-story-categories_select".
 */
export interface SuccessStoryCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  color?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        focusKeyword?: T;
        dismissedWarnings?:
          | T
          | {
              ruleId?: T;
              id?: T;
            };
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        twitterTitle?: T;
        twitterDescription?: T;
        twitterImage?: T;
        robots?:
          | T
          | {
              index?: T;
              noindex?: T;
              follow?: T;
              nofollow?: T;
              noarchive?: T;
              nosnippet?: T;
              noimageindex?: T;
              maxSnippet?: T;
              maxImagePreview?: T;
              maxVideoPreview?: T;
            };
        jsonLd?:
          | T
          | {
              faq?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              howTo?:
                | T
                | {
                    name?: T;
                    description?: T;
                    step?:
                      | T
                      | {
                          name?: T;
                          text?: T;
                          url?: T;
                          image?: T;
                          id?: T;
                        };
                  };
              advancedOverride?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  heroTitle?: string | null;
  heroDescription?: string | null;
  /**
   * The default site name used in SEO titles.
   */
  siteTitle?: string | null;
  /**
   * The default meta description for the site.
   */
  siteDescription?: string | null;
  /**
   * The default Open Graph image used when a page lacks a specific image.
   */
  defaultOgImage?: (number | null) | Media;
  defaultTwitterCard?: ('summary' | 'summary_large_image') | null;
  /**
   * Configure default robots meta tags for search engines.
   */
  defaultRobots?: {
    /**
     * Allow search engines to index pages
     */
    index?: boolean | null;
    /**
     * Prevent indexing
     */
    noindex?: boolean | null;
    /**
     * Allow following links
     */
    follow?: boolean | null;
    /**
     * Prevent following links
     */
    nofollow?: boolean | null;
    /**
     * Do not show a cached link in search results
     */
    noarchive?: boolean | null;
    /**
     * Do not show a text snippet or video preview
     */
    nosnippet?: boolean | null;
    /**
     * Do not index images on this page
     */
    noimageindex?: boolean | null;
    /**
     * Maximum text-snippet length (in characters)
     */
    maxSnippet?: number | null;
    /**
     * Maximum size of an image preview
     */
    maxImagePreview?: ('none' | 'standard' | 'large') | null;
    /**
     * Maximum video snippet length (in seconds)
     */
    maxVideoPreview?: number | null;
  };
  verificationTags?: {
    /**
     * Google Search Console verification ID
     */
    google?: string | null;
    /**
     * Bing Webmaster Tools verification ID
     */
    bing?: string | null;
  };
  organizationSchema?: {
    name?: string | null;
    url?: string | null;
    logo?: (number | null) | Media;
    sameAs?:
      | {
          url?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  contactEmail?: string | null;
  socialLinks?:
    | {
        platform?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  newsletterPopup: {
    isActive?: boolean | null;
    title: string;
    description: string;
    buttonText: string;
    buttonLink: string;
  };
  trustedBrands?: {
    logos?:
      | {
          logo?: (number | null) | Media;
          alt?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-settings".
 */
export interface HomepageSetting {
  id: number;
  /**
   * Select up to 3 categories to display on the blog homepage.
   */
  curatedCategories: (number | Category)[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  heroTitle?: T;
  heroDescription?: T;
  siteTitle?: T;
  siteDescription?: T;
  defaultOgImage?: T;
  defaultTwitterCard?: T;
  defaultRobots?:
    | T
    | {
        index?: T;
        noindex?: T;
        follow?: T;
        nofollow?: T;
        noarchive?: T;
        nosnippet?: T;
        noimageindex?: T;
        maxSnippet?: T;
        maxImagePreview?: T;
        maxVideoPreview?: T;
      };
  verificationTags?:
    | T
    | {
        google?: T;
        bing?: T;
      };
  organizationSchema?:
    | T
    | {
        name?: T;
        url?: T;
        logo?: T;
        sameAs?:
          | T
          | {
              url?: T;
              id?: T;
            };
      };
  contactEmail?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  newsletterPopup?:
    | T
    | {
        isActive?: T;
        title?: T;
        description?: T;
        buttonText?: T;
        buttonLink?: T;
      };
  trustedBrands?:
    | T
    | {
        logos?:
          | T
          | {
              logo?: T;
              alt?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-settings_select".
 */
export interface HomepageSettingsSelect<T extends boolean = true> {
  curatedCategories?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}