export const transitionWords = [
  'accordingly', 'additionally', 'after', 'afterward', 'afterwards', 'albeit', 'also',
  'although', 'altogether', 'another', 'anyway', 'as a result', 'as an illustration',
  'as long as', 'as soon as', 'as well as', 'at any rate', 'at first', 'at last',
  'at least', 'at the same time', 'basically', 'because', 'before', 'besides',
  'briefly', 'but', 'by all means', 'by and large', 'by comparison', 'by contrast',
  'by no means', 'certainly', 'chiefly', 'comparatively', 'consequently',
  'conversely', 'correspondingly', 'despite', 'due to', 'during', 'earlier',
  'either', 'equally', 'especially', 'even if', 'even so', 'even though',
  'eventually', 'evidently', 'explicitly', 'finally', 'first', 'firstly',
  'for example', 'for instance', 'for one thing', 'for that reason', 'for the most part',
  'for this reason', 'formerly', 'forthwith', 'frequently', 'further', 'furthermore',
  'generally', 'given that', 'granted', 'hence', 'here', 'however', 'identically',
  'if', 'if so', 'in a word', 'in addition', 'in brief', 'in case', 'in conclusion',
  'in contrast', 'in detail', 'in due time', 'in effect', 'in either case', 'in essence',
  'in fact', 'in general', 'in light of', 'in like manner', 'in order to',
  'in other words', 'in particular', 'in reality', 'in short', 'in spite of',
  'in sum', 'in summary', 'in that case', 'in the end', 'in the first place',
  'in the meantime', 'in the same way', 'in truth', 'in conclusion', 'indeed',
  'instead', 'just as', 'just like', 'later', 'lest', 'likewise', 'meanwhile',
  'moreover', 'namely', 'naturally', 'neither', 'nevertheless', 'next', 'nonetheless',
  'nor', 'not only', 'notably', 'now', 'now that', 'obviously', 'of course',
  'on the contrary', 'on the one hand', 'on the other hand', 'on the whole',
  'once', 'or', 'otherwise', 'overall', 'particularly', 'presently', 'previously',
  'prior to', 'provided that', 'rather', 'regardless', 'second', 'secondly',
  'shortly', 'significantly', 'similarly', 'simultaneously', 'since', 'so',
  'so as to', 'so that', 'soon', 'specifically', 'still', 'straightaway',
  'subsequently', 'such as', 'surely', 'surprisingly', 'than', 'that is',
  'then', 'thereafter', 'therefore', 'thereupon', 'third', 'thirdly', 'though',
  'thus', 'to begin with', 'to clarify', 'to conclude', 'to demonstrate',
  'to emphasize', 'to illustrate', 'to put it differently', 'to put it another way',
  'to summarize', 'to sum up', 'too', 'ultimately', 'undeniably', 'undoubtedly',
  'unless', 'unlike', 'until', 'upon', 'usually', 'when', 'whenever', 'where',
  'whereas', 'wherever', 'whether', 'while', 'with this in mind', 'yet'
]
